#!/bin/bash
# Script to control PLATO interface process

phost=cyberserv.org
snd_dev=/dev/snd/controlC0

function delay_boot() {
	echo "$1 - restarting in 15 seconds"
	sync
	sleep 15
	sync
	sync
	reboot
	sleep 5
	exit 1
}

test -c ${snd_dev} ||
	delay_boot "Sound device missing"

while ! ping -q -c 1 -w 10 ${phost} &> /dev/null; do
	echo "Waiting for ${phost}..."
done

/usr/local/bin/plato_if ${phost} &> /var/volatile/log/platod.log ||
	delay_boot "plato_if failed"
