#!/bin/bash
# Script to control PLATO interface process

phost=cyberserv.org
snd_dev=/dev/snd/controlC0
ulb=/usr/local/bin

function delay_boot() {
	echo "$1 - restarting in 20 seconds"
	${ulb}/platomsg "$1 - restarting in 20 seconds"
	sync
	sleep 20
	sync
	sync
	reboot
	sleep 10
	exit 1
}

test -c ${snd_dev} ||
	delay_boot "Sound device missing"

while ! ping -q -c 1 -w 10 ${phost} &> /dev/null; do
	echo "Waiting for ${phost}..."
	${ulb}/platomsg "Waiting for ${phost}..."
done

/usr/local/bin/plato_if ${phost} &> /var/volatile/log/platod.log ||
	delay_boot "plato_if failed"
